server:
  port: 8083
  servlet:
    context-path: /search

spring:
  application:
    name: itrip-search

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nocos
